// Action Type Constants
export const SEND_NOTIFICATION_SUBMIT = 'SEND_NOTIFICATION_SUBMIT';
export const SEND_NOTIFICATION_SUCCESS = 'SEND_NOTIFICATION_SUCCESS';
export const SEND_NOTIFICATION_FAILURE = 'SEND_NOTIFICATION_FAILURE';